ミニバッチ学習

In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(x_train, t_train), (x_test, t_test) = mnist.load_data()

t_train = to_categorical(t_train)
x_train = x_train.reshape(60000, 784)
print(x_train.shape)
print(t_train.shape)

(60000, 784)
(60000, 10)


In [2]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

In [3]:
np.random.choice(60000, 10)

array([ 3718,  2196, 32326, 29378, 28142,  6683, 10220,  9851, 31891,
        8572])

In [4]:
batch_mask

array([13800, 19304,  4074,  9772, 50681, 31303, 56840,  7170, 41934,
       26486])

[バッチ対応版]交差エントロピー誤差の実装

In [5]:
def cross_entropy_error(y, t):
    if y.ndim ==1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y)) / batch_size

In [6]:
y = np.array([0.1, 0.8, 0.1])
t = np.array([0, 1, 0])

print(y)
print(y.reshape(1, y.size))

cross_entropy_error(y, t)

[0.1 0.8 0.1]
[[0.1 0.8 0.1]]


0.2231435513142097

In [7]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t])) / batch_size

In [8]:
y = np.array([0.1, 0.8, 0.1])
t = np.array([1])

cross_entropy_error(y, t)

0.2231435513142097